### ISSUE TITLE
try was added with 5.33.7

### ISSUE THREAD

**Issue by matthewlenz** [Dual-Life/experimental#11]
Unless I'm mistaken (very likely) the try functionality was added in 5.33.7 (not 5.33.6 per the recent commit).

https://perldoc.perl.org/5.33.7/perldelta#Experimental-Try/Catch-Syntax

**Comment by Leont** [comment]
It seems you're right. I'll update it (though in practice it doesn't matter since no one will actually run 5.33.6 anymore).

**Comment by Leont** [comment]
Fixed 0.025
