### ISSUE TITLE
lexical topic removed in 5.24

### ISSUE THREAD

**Issue by rjbs** [Dual-Life/experimental#4]
Please import our `cpan/experimental/t/basic.t` from blead and cut a new release.

Thanks! 😄

**Comment by Leont** [comment]
I should possibly add some helpful error message about it's removal if it's loaded on 5.24, if feature doesn't do that already.

**Comment by xsawyerx** [comment]
Ping?

**Comment by Leont** [comment]
This was fixed in 0.015
